### ISSUE TITLE
 DefaultCPUAllocator: not enough memory: you tried to allocate 16777216000 bytes. Buy new RAM!

### ISSUE THREAD

**Issue by HaoyuanXu** [LeapMind/MLF-SC#41]
When I run 'python main.py train cfg/sample_config.yml '
and even set batch_size==1,
the issue raised as follows:

loading images:  99%|█████████████████████████████████████████████████
loading images: 100%|█████████████████████████████████████████████████
loading images: 100%|█████████████████████████████████████████████████
█████████████| 1000/1000 [00:18<00:00, 54.16it/s]
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 74, in main
    model.train()
  File "D:\research\comp_data\MLF-SC\src\models.py", line 53, in train
    batch_img = p(batch_img)
  File "D:\research\comp_data\MLF-SC\src\preprocessor.py", line 95, in __call__
    x = f(x)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried
to allocate 16777216000 bytes. Buy new RAM!

Well, would you figure out the way to solve this issue?
Thank you in advance!

**Comment by a-hanamoto** [comment]
Thank you! There are two options.
1. increase the amount of (virtual) memory
2. decrease the number of training images
Usually, 10-100 images are enough to train, so I recommend that you reduce the training images.

**Comment by HaoyuanXu** [comment]
Thanks for your  reply!
But it's weird ... I have already set the batch_size==1  , it still raised this issue.
And the bytes is so much large(My dataset isn't that big)
Maybe it's the issue raised when reading the image dataset?

**Comment by a-hanamoto** [comment]
The current system tries to load all the images regardless of batch_size so that’s why. Sorry for inconvenience
