### ISSUE TITLE
GPU utilization 

### ISSUE THREAD

**Issue by ArunPrasad46** [LeapMind/MLF-SC#42]
First of all thanks for the work.

I was trying to use the test section for the prediction of anomalies from the dataset. The time taken for prediction is too long. 

Is there any option for utilizing GPU with the code that can improve the execution time?

**Comment by a-hanamoto** [comment]
Sorry for the late reply.
There is no option, but we can utilize GPU by modifying https://github.com/LeapMind/MLF-SC/blob/master/src/preprocessor.py#L82 this class.
